### ISSUE TITLE
Compilation errors in audiodecodermediafoundation.cpp

### ISSUE THREAD

**Issue by MrBlenny** [Wickedlasers/libLaserdockCore#1]
This could very well be a very stupid mistake. Nonetheless...

I've followed the instructions in the readme. I'm getting a few compilation errors in `audiodecodermediafoundation.cpp`, trying to compile default for 32bit windows using `Qt/5.11.1/mingw53_32`. Could you point me in the right direction? My complete lack of understanding of the C++ and QT world makes it a little difficult :)

<img width="1346" alt="errors" src="https://user-images.githubusercontent.com/9685048/43630611-20c9c5da-9744-11e8-81be-2a9bbdfbe004.png">

**Comment by LauraLaureus** [comment]
Hi @MrBlenny !! Have you already solved this? I have already compilated this project in Windows using win VS2015 compilers maybe I can help if you are still in need.

**Comment by MrBlenny** [comment]
Nope, haven't solved yet. What config was required to get it compiling with VS2015?

**Comment by LauraLaureus** [comment]
I used [CMake](https://cmake.org/)  to generate the Visual Studio Project with all the libs. 
If you are going to build the example there is also a couple of cmake details to cover.

The first one is that the CMAKEList.txt of the example needs to be modified since ${CMAKE_BUILD_TYPE} is not set for visual studio compilers ([ref](https://stackoverflow.com/questions/24460486/cmake-build-type-not-being-used-in-cmakelists-txt)).

This means the var BUILD_SUB_PATH (which takes its value from ${CMAKE_BUILD_TYPE}  ) variable used in the deploy section should be replaced with the word "Debug" in lines 102,113,118, (at least).

The other detail is a error in the source code, that I'll pull request in a moment so you will not have to worry about it :).

**Comment by gavrushkin** [comment]
MrBlenny,
We support only msvc2015 compiler. You should be able to compile it from Qt Creator without any problems. 

Laura, 
Thank you for your comments. Visual Studio is not a priority but if you have some nice patches feel free to create pull request :)

**Comment by gavrushkin** [comment]
Closing this issue as irrelevant
